# Generated by Django 4.0.6 on 2022-07-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_shippingaddress_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='transaction_id',
        ),
    ]
